services:
  fika-server:
    container_name: spt-server
    image: fika-spt-server-docker:latest
    ports:
      - 6969:6969
    environment:
      - SPT_BACKEND_IP=192.168.1.15 # 0.0.0.0 will listen to all networks, change this to tell the SPT client the IP to connect in order to load profiles
      - SPT_BACKEND_PORT=443 # If you use a reverse proxy and need a custom port to reach from the client to your reverse proxy before connecting with this container

      # Provide the uid/gid of the user, or it will default to 0 (root)
      - UID=1000
      - GID=1000
      # FIKA_MODE controls Fika installation and updates
      # Options: disabled (no Fika), install (install and validate), auto-update (auto-update on mismatch), custom (skip validation)
      - FIKA_MODE=auto-update
      - FIKA_VERSION=2.4.0

      # If you want the container to update SPT automatically if it detects the SPT server version does not match expected version, set this to true
      - AUTO_UPDATE_SPT=true

      # If you don't want the container to change the file ownership of your server files, set this to false
      - TAKE_OWNERSHIP=true

      # If you don't want to automatically back up profiles, set this to false
      - ENABLE_PROFILE_BACKUPS=true

      # If you want to override the timezone. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for a list of valid TZ codes
      # - TZ=

      # - INSTALL_OTHER_MODS=true
      # - MOD_URLS_TO_DOWNLOAD= >
      #     https://github.com/DrakiaXYZ/SPT-EasyAmmoNames-CSharp/releases/download/2.1.0/EasyAmmoNames-2.1.0.7z
      #     other URLS for SP Mods 
      # If you want to override the SPT version for this container, set this variable to the version string
      # The version should follow the release archive name format <SPT_VERSION>-<EFT_BUILD_NUMBER>-<SPT_GIT_SHA>
      # user folder backups will be disabled. You can find the archives from the releases here https://github.com/SP-Tushonka/build

      # - FORCE_SPT_VERSION=4.0.2-40087-0df4ae7
    volumes:
      # Set this to the directory on your host containing either your existing SPT server files or where you wish to store a new SPT server install
      - ./k-server:/opt/server
